### ISSUE TITLE
have an example to use this virtio lib

### ISSUE THREAD

**Issue by hwwei521** [CTSRD-CHERI/FreeRTOS-Labs-libvirtio#1]
If there is any plan to explain how to use this virtio lib or add an explanation file of readme.txt

**Comment by heshamelmatary** [comment]
You could build `main_servers` demo for QEMU (or FETT) as per https://github.com/CTSRD-CHERI/FreeRTOS-Demos-CHERI-RISC-V. The TCP/IP stack uses VirtIO as a driver [here](https://github.com/CTSRD-CHERI/FreeRTOS-Plus-TCP/blob/hmka2/portable/NetworkInterface/virtio/NetworkInterface.c)
